logging:
  file:
    name: ./logs/ZuulProxyAPIGateWay.log
  pattern:
    console: '"%d{yyyy-MM-dd HH:mm:ss} - %msg%n"'
    file: '"%d{yyyy-MM-dd HH:mm:ss} [%thread]  %-5level %logger{36} -%msg%n"'
server:
  port: 8080
spring:
  application:
    name: CC-ZUULPROXYAPIGATEWAY
###########################################################################
  cloud:
    gateway:
      routes:
      - id: CC-CONSUMERUSERSERVICE
        uri: lb://CC-CONSUMERUSERSERVICE
        predicates:
            - Path=/consumeruserservice/**
        filters:
           - name: CircuitBreaker
             args:
               name: CC-CONSUMERUSERSERVICE
               fallbackuri: forward:/consumeruserservicefallback
######################################EEEEEEEEEEE######################################
      - id: CC-STUDENTSERVICE
        uri: lb://CC-STUDENTSERVICE
        predicates:
            - Path=/studentservice/**
        filters:
            - name: CircuitBreaker
              args:
                name: CC-STUDENTSERVICE
                fallbackuri: forward:/studentservicefallback
                
########################################################################                
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000